### ISSUE TITLE
Scan2Excel will be an interesting work!

### ISSUE THREAD

**Issue by 0x1orz** [Aniruddha-Tapas/Android_OpenCV_Scan2Excel#1]
Hey! Scan2Excel will be an instersting work!
I am also studying tenserflow with Python for the Scan2Excel in PC to dealing with the scanned  tabular digit figure.

**Comment by Aniruddha-Tapas** [comment]
Yeah. But due to the poor qualities of the android cameras, digits in a table are not being captured properly for recognition using TensorFlow. Hence the project is stalled. Still trying to find robust solutions for the problem. If you happen to find a workaround, please send a pull request. :)
